// Command generate emits the desktop DTOs and OpenAPI dashboard schemas from
// the same Go types consumed by the TUI and manager. Run with -check in CI.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"time"

	dashboard "github.com/ejpir/gantry/internal/dashboard/api"
	"github.com/ejpir/gantry/internal/packetcapture"
	"github.com/ejpir/gantry/internal/secret"
)

var types = map[string]reflect.Type{}
var timeType = reflect.TypeFor[time.Time]()
var secretType = reflect.TypeFor[secret.Value]()
var firstCap = regexp.MustCompile(`(.)([A-Z][a-z]+)`)
var allCap = regexp.MustCompile(`([a-z0-9])([A-Z])`)

func name(t reflect.Type) string {
	if t.PkgPath() == reflect.TypeFor[packetcapture.Request]().PkgPath() {
		switch t.Name() {
		case "Request":
			return "PacketRequest"
		case "Snapshot":
			return "PacketSnapshot"
		}
	}
	if t == reflect.TypeFor[dashboard.Snapshot]() {
		return "DashboardData"
	}
	return t.Name()
}
func visit(t reflect.Type) {
	if t == timeType || t == secretType {
		return
	}
	switch t.Kind() {
	case reflect.Pointer, reflect.Slice:
		visit(t.Elem())
	case reflect.Struct:
		n := name(t)
		if _, ok := types[n]; ok {
			return
		}
		types[n] = t
		for i := 0; i < t.NumField(); i++ {
			visit(t.Field(i).Type)
		}
	}
}
func fieldName(f reflect.StructField) (string, bool) {
	parts := strings.Split(f.Tag.Get("json"), ",")
	n := parts[0]
	if n == "" {
		n = f.Name
	}
	return n, len(parts) > 1 && parts[1] == "omitempty"
}
func rust(t reflect.Type) string {
	if t == timeType {
		return "String"
	}
	if t == secretType {
		return "crate::wire::SecretInput"
	}
	switch t.Kind() {
	case reflect.Pointer:
		return "Option<" + rust(t.Elem()) + ">"
	case reflect.Slice:
		if t.Elem().Kind() == reflect.Uint8 {
			return "String"
		}
		return "Vec<" + rust(t.Elem()) + ">"
	case reflect.Struct:
		return name(t)
	case reflect.String:
		return "String"
	case reflect.Bool:
		return "bool"
	case reflect.Uint16:
		return "u16"
	case reflect.Uint32:
		return "u32"
	case reflect.Uint, reflect.Uint64:
		return "u64"
	case reflect.Int, reflect.Int64:
		return "i64"
	default:
		panic(t.String())
	}
}
func schema(t reflect.Type) map[string]any {
	if t == timeType {
		return map[string]any{"type": "string", "format": "date-time"}
	}
	if t == secretType {
		return map[string]any{"type": "string", "writeOnly": true}
	}
	switch t.Kind() {
	case reflect.Pointer:
		return schema(t.Elem())
	case reflect.Struct:
		return map[string]any{"$ref": "#/components/schemas/Wire" + name(t)}
	case reflect.Slice:
		if t.Elem().Kind() == reflect.Uint8 {
			return map[string]any{"type": "string", "format": "byte"}
		}
		return map[string]any{"type": "array", "items": schema(t.Elem()), "nullable": true}
	case reflect.String:
		return map[string]any{"type": "string"}
	case reflect.Bool:
		return map[string]any{"type": "boolean"}
	default:
		s := map[string]any{"type": "integer"}
		if t.Kind() == reflect.Uint || t.Kind() == reflect.Uint32 || t.Kind() == reflect.Uint64 {
			s["minimum"] = 0
		}
		return s
	}
}
func main() {
	root := flag.String("root", ".", "repository root")
	check := flag.Bool("check", false, "fail rather than update stale generated files")
	flag.Parse()
	for _, t := range []reflect.Type{reflect.TypeFor[dashboard.HostSnapshot](), reflect.TypeFor[dashboard.ActionRequest](), reflect.TypeFor[dashboard.ActionResult](), reflect.TypeFor[packetcapture.Request](), reflect.TypeFor[packetcapture.Snapshot]()} {
		visit(t)
	}
	names := make([]string, 0, len(types))
	for n := range types {
		names = append(names, n)
	}
	sort.Strings(names)
	var rs, schemas bytes.Buffer
	rs.WriteString("// Generated by internal/dashboard/api/generate. DO NOT EDIT.\nuse serde::{Deserialize, Serialize};\n\n")
	schemas.WriteString("    # BEGIN GENERATED DASHBOARD SCHEMAS\n")
	for _, n := range names {
		t := types[n]
		rs.WriteString("#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]\n")
		if n != "HostSnapshot" {
			rs.WriteString("#[serde(default)]\n")
		}
		fmt.Fprintf(&rs, "pub struct %s {\n", n)
		props := map[string]any{}
		required := []string{}
		for i := 0; i < t.NumField(); i++ {
			f := t.Field(i)
			jsonName, omit := fieldName(f)
			normalized := strings.NewReplacer("VCPUs", "Vcpus", "MiB", "Mib").Replace(f.Name)
			sn := strings.ToLower(allCap.ReplaceAllString(firstCap.ReplaceAllString(normalized, "${1}_${2}"), "${1}_${2}"))
			if sn == "type" || sn == "ref" {
				sn = "r#" + sn
			}
			fmt.Fprintf(&rs, "    #[serde(rename = %q", jsonName)
			if f.Type.Kind() == reflect.Pointer {
				rs.WriteString(", skip_serializing_if = \"Option::is_none\"")
			} else if omit {
				rs.WriteString(", skip_serializing_if = \"crate::wire::is_default\"")
			}
			if f.Type.Kind() == reflect.Slice && f.Type.Elem().Kind() != reflect.Uint8 {
				rs.WriteString(", default, deserialize_with = \"crate::wire::null_vec\"")
			}
			rs.WriteString(")]\n")
			fmt.Fprintf(&rs, "    pub %s: %s,\n", sn, rust(f.Type))
			props[jsonName] = schema(f.Type)
			if !omit {
				required = append(required, jsonName)
			}
		}
		rs.WriteString("}\n\n")
		s := map[string]any{"type": "object", "properties": props}
		if len(required) > 0 {
			s["required"] = required
		}
		if n == "ActionRequest" {
			variants := []any{}
			for _, action := range dashboard.ActionNames() {
				fields := map[string]any{"action": map[string]any{"type": "string", "enum": []string{action}}}
				required := []string{"action"}
				if payload := dashboard.ActionPayload(action); payload != "" {
					fields[payload] = props[payload]
					required = append(required, payload)
				}
				variants = append(variants, map[string]any{"type": "object", "additionalProperties": false, "required": required, "properties": fields})
			}
			s = map[string]any{"oneOf": variants}
		}
		b, err := json.Marshal(s)
		if err != nil {
			panic(err)
		}
		fmt.Fprintf(&schemas, "    Wire%s: %s\n", n, b)
	}
	schemas.WriteString("    # END GENERATED DASHBOARD SCHEMAS\n")
	update := func(path string, content []byte) {
		old, err := os.ReadFile(path)
		if err == nil && bytes.Equal(old, content) {
			return
		}
		if *check {
			fmt.Fprintln(os.Stderr, "stale generated file:", path)
			os.Exit(1)
		}
		if err := os.WriteFile(path, content, 0644); err != nil {
			panic(err)
		}
	}
	// rustfmt skips this generated module; formatting is deterministic here.
	update(filepath.Join(*root, "desktop/src/dashboard_wire.rs"), append(bytes.TrimRight(rs.Bytes(), "\n"), '\n'))
	path := filepath.Join(*root, "api/managerapi/openapi.yaml")
	old, err := os.ReadFile(path)
	if err != nil {
		panic(err)
	}
	prefix := strings.Split(string(old), "    # BEGIN GENERATED DASHBOARD SCHEMAS")[0]
	aliases := map[string]string{"DashboardSnapshot": "HostSnapshot", "DashboardActionRequest": "ActionRequest", "DashboardActionResult": "ActionResult", "PacketCaptureRequest": "PacketRequest", "PacketCaptureSnapshot": "PacketSnapshot"}
	var canonical strings.Builder
	skip := false
	for _, line := range strings.SplitAfter(prefix, "\n") {
		if skip && (strings.HasPrefix(line, "      ") || strings.TrimSpace(line) == "") {
			continue
		}
		skip = false
		if replacement, ok := aliases[strings.TrimSuffix(strings.TrimSpace(line), ":")]; ok && strings.HasPrefix(line, "    ") && !strings.HasPrefix(line, "     ") {
			canonical.WriteString(line)
			fmt.Fprintf(&canonical, "      $ref: \"#/components/schemas/Wire%s\"\n", replacement)
			skip = true
		} else {
			canonical.WriteString(line)
		}
	}
	update(path, append([]byte(canonical.String()), schemas.Bytes()...))
}
