// Generated by internal/dashboard/api/generate. DO NOT EDIT.
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ActionRequest {
    #[serde(rename = "action")]
    pub action: String,
    #[serde(rename = "value", skip_serializing_if = "crate::wire::is_default")]
    pub value: String,
    #[serde(rename = "sandboxConfig", skip_serializing_if = "Option::is_none")]
    pub sandbox_config: Option<SandboxConfigRequest>,
    #[serde(rename = "ruleRequest", skip_serializing_if = "Option::is_none")]
    pub rule_request: Option<RuleRequest>,
    #[serde(rename = "rule", skip_serializing_if = "Option::is_none")]
    pub rule: Option<Rule>,
    #[serde(rename = "traffic", skip_serializing_if = "Option::is_none")]
    pub traffic: Option<Traffic>,
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<SecretRequest>,
    #[serde(rename = "secretRow", skip_serializing_if = "Option::is_none")]
    pub secret_row: Option<Secret>,
    #[serde(rename = "mcpRemote", skip_serializing_if = "Option::is_none")]
    pub mcp_remote: Option<MCPRemoteRequest>,
    #[serde(rename = "mcpFilesystem", skip_serializing_if = "Option::is_none")]
    pub mcp_filesystem: Option<MCPFilesystemRequest>,
    #[serde(rename = "mcpServer", skip_serializing_if = "Option::is_none")]
    pub mcp_server: Option<MCPServer>,
    #[serde(rename = "registry", skip_serializing_if = "Option::is_none")]
    pub registry: Option<RegistryLoginRequest>,
    #[serde(rename = "share", skip_serializing_if = "Option::is_none")]
    pub share: Option<ShareRequest>,
    #[serde(rename = "sharePlan", skip_serializing_if = "Option::is_none")]
    pub share_plan: Option<SharePlan>,
    #[serde(rename = "mount", skip_serializing_if = "Option::is_none")]
    pub mount: Option<Mount>,
    #[serde(rename = "portRequest", skip_serializing_if = "Option::is_none")]
    pub port_request: Option<PortRequest>,
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<PortMutationRequest>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ActionResult {
    #[serde(rename = "restartRequired", skip_serializing_if = "crate::wire::is_default")]
    pub restart_required: bool,
    #[serde(rename = "policy", skip_serializing_if = "Option::is_none")]
    pub policy: Option<PolicyResult>,
    #[serde(rename = "sharePlan", skip_serializing_if = "Option::is_none")]
    pub share_plan: Option<SharePlan>,
    #[serde(rename = "portSpec", skip_serializing_if = "crate::wire::is_default")]
    pub port_spec: String,
    #[serde(rename = "warning", skip_serializing_if = "crate::wire::is_default")]
    pub warning: String,
    #[serde(rename = "count", skip_serializing_if = "crate::wire::is_default")]
    pub count: i64,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct AuditDecision {
    #[serde(rename = "effect")]
    pub effect: String,
    #[serde(rename = "action")]
    pub action: String,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "rules", default, deserialize_with = "crate::wire::null_vec")]
    pub rules: Vec<String>,
    #[serde(rename = "organization")]
    pub organization: String,
    #[serde(rename = "revision")]
    pub revision: String,
    #[serde(rename = "profile")]
    pub profile: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct AuditEvent {
    #[serde(rename = "Remote")]
    pub remote: String,
    #[serde(rename = "Sandbox")]
    pub sandbox: String,
    #[serde(rename = "Line")]
    pub line: String,
    #[serde(rename = "Occurrence")]
    pub occurrence: i64,
    #[serde(rename = "Decision", skip_serializing_if = "Option::is_none")]
    pub decision: Option<AuditDecision>,
    #[serde(rename = "Error")]
    pub error: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct DashboardData {
    #[serde(rename = "Sandboxes", default, deserialize_with = "crate::wire::null_vec")]
    pub sandboxes: Vec<Sandbox>,
    #[serde(rename = "Traffic", default, deserialize_with = "crate::wire::null_vec")]
    pub traffic: Vec<Traffic>,
    #[serde(rename = "Rules", default, deserialize_with = "crate::wire::null_vec")]
    pub rules: Vec<Rule>,
    #[serde(rename = "Mounts", default, deserialize_with = "crate::wire::null_vec")]
    pub mounts: Vec<Mount>,
    #[serde(rename = "Ports", default, deserialize_with = "crate::wire::null_vec")]
    pub ports: Vec<Port>,
    #[serde(rename = "Secrets", default, deserialize_with = "crate::wire::null_vec")]
    pub secrets: Vec<Secret>,
    #[serde(rename = "MCPServers", default, deserialize_with = "crate::wire::null_vec")]
    pub mcp_servers: Vec<MCPServer>,
    #[serde(rename = "Audit", default, deserialize_with = "crate::wire::null_vec")]
    pub audit: Vec<AuditEvent>,
    #[serde(rename = "Images", default, deserialize_with = "crate::wire::null_vec")]
    pub images: Vec<Image>,
    #[serde(rename = "Registries", default, deserialize_with = "crate::wire::null_vec")]
    pub registries: Vec<RegistryAuth>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct HostSnapshot {
    #[serde(rename = "snapshot")]
    pub snapshot: DashboardData,
    #[serde(rename = "resourceLimits")]
    pub resource_limits: ResourceLimits,
    #[serde(rename = "kernelChoices", skip_serializing_if = "crate::wire::is_default", default, deserialize_with = "crate::wire::null_vec")]
    pub kernel_choices: Vec<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct Image {
    #[serde(rename = "Remote")]
    pub remote: String,
    #[serde(rename = "Ref")]
    pub r#ref: String,
    #[serde(rename = "Digest")]
    pub digest: String,
    #[serde(rename = "Arch")]
    pub arch: String,
    #[serde(rename = "Created")]
    pub created: String,
    #[serde(rename = "Size")]
    pub size: i64,
    #[serde(rename = "InUse")]
    pub in_use: bool,
    #[serde(rename = "User")]
    pub user: String,
    #[serde(rename = "WorkingDir")]
    pub working_dir: String,
    #[serde(rename = "Entrypoint", default, deserialize_with = "crate::wire::null_vec")]
    pub entrypoint: Vec<String>,
    #[serde(rename = "Cmd", default, deserialize_with = "crate::wire::null_vec")]
    pub cmd: Vec<String>,
    #[serde(rename = "EnvCount")]
    pub env_count: i64,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct MCPFilesystemRequest {
    #[serde(rename = "Sandbox")]
    pub sandbox: String,
    #[serde(rename = "Root")]
    pub root: String,
    #[serde(rename = "User")]
    pub user: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct MCPRemoteRequest {
    #[serde(rename = "Sandbox")]
    pub sandbox: String,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "URL")]
    pub url: String,
    #[serde(rename = "AuthKind")]
    pub auth_kind: String,
    #[serde(rename = "AuthHeader")]
    pub auth_header: String,
    #[serde(rename = "AuthRef")]
    pub auth_ref: String,
    #[serde(rename = "Allow", default, deserialize_with = "crate::wire::null_vec")]
    pub allow: Vec<String>,
    #[serde(rename = "Deny", default, deserialize_with = "crate::wire::null_vec")]
    pub deny: Vec<String>,
    #[serde(rename = "Redact", default, deserialize_with = "crate::wire::null_vec")]
    pub redact: Vec<String>,
    #[serde(rename = "Replace")]
    pub replace: bool,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct MCPServer {
    #[serde(rename = "Remote")]
    pub remote: String,
    #[serde(rename = "Sandbox")]
    pub sandbox: String,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "Type")]
    pub r#type: String,
    #[serde(rename = "URL")]
    pub url: String,
    #[serde(rename = "AuthKind")]
    pub auth_kind: String,
    #[serde(rename = "AuthHeader")]
    pub auth_header: String,
    #[serde(rename = "AuthRef")]
    pub auth_ref: String,
    #[serde(rename = "Allow", default, deserialize_with = "crate::wire::null_vec")]
    pub allow: Vec<String>,
    #[serde(rename = "Deny", default, deserialize_with = "crate::wire::null_vec")]
    pub deny: Vec<String>,
    #[serde(rename = "Redact", default, deserialize_with = "crate::wire::null_vec")]
    pub redact: Vec<String>,
    #[serde(rename = "Root")]
    pub root: String,
    #[serde(rename = "User")]
    pub user: String,
    #[serde(rename = "State")]
    pub state: String,
    #[serde(rename = "Error")]
    pub error: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct Mount {
    #[serde(rename = "Remote")]
    pub remote: String,
    #[serde(rename = "Sandbox")]
    pub sandbox: String,
    #[serde(rename = "Tag")]
    pub tag: String,
    #[serde(rename = "Host")]
    pub host: String,
    #[serde(rename = "VM")]
    pub vm: String,
    #[serde(rename = "Guest")]
    pub guest: String,
    #[serde(rename = "ReadOnly")]
    pub read_only: bool,
    #[serde(rename = "UID", skip_serializing_if = "Option::is_none")]
    pub uid: Option<u32>,
    #[serde(rename = "GID", skip_serializing_if = "Option::is_none")]
    pub gid: Option<u32>,
    #[serde(rename = "State")]
    pub state: String,
    #[serde(rename = "Error")]
    pub error: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct Packet {
    #[serde(rename = "sequence")]
    pub sequence: u64,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "direction")]
    pub direction: String,
    #[serde(rename = "allowed")]
    pub allowed: bool,
    #[serde(rename = "length")]
    pub length: i64,
    #[serde(rename = "data")]
    pub data: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct PacketRequest {
    #[serde(rename = "start", skip_serializing_if = "crate::wire::is_default")]
    pub start: bool,
    #[serde(rename = "clear", skip_serializing_if = "crate::wire::is_default")]
    pub clear: bool,
    #[serde(rename = "stop", skip_serializing_if = "crate::wire::is_default")]
    pub stop: bool,
    #[serde(rename = "after", skip_serializing_if = "crate::wire::is_default")]
    pub after: u64,
    #[serde(rename = "max_packets", skip_serializing_if = "crate::wire::is_default")]
    pub max_packets: i64,
    #[serde(rename = "max_bytes", skip_serializing_if = "crate::wire::is_default")]
    pub max_bytes: i64,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct PacketSnapshot {
    #[serde(rename = "active")]
    pub active: bool,
    #[serde(rename = "packets", skip_serializing_if = "crate::wire::is_default", default, deserialize_with = "crate::wire::null_vec")]
    pub packets: Vec<Packet>,
    #[serde(rename = "next", skip_serializing_if = "crate::wire::is_default")]
    pub next: u64,
    #[serde(rename = "latest", skip_serializing_if = "crate::wire::is_default")]
    pub latest: u64,
    #[serde(rename = "oldest", skip_serializing_if = "crate::wire::is_default")]
    pub oldest: u64,
    #[serde(rename = "evicted", skip_serializing_if = "crate::wire::is_default")]
    pub evicted: u64,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct PolicyResult {
    #[serde(rename = "Path")]
    pub path: String,
    #[serde(rename = "Description")]
    pub description: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct Port {
    #[serde(rename = "Remote")]
    pub remote: String,
    #[serde(rename = "Sandbox")]
    pub sandbox: String,
    #[serde(rename = "Bind")]
    pub bind: String,
    #[serde(rename = "Guest")]
    pub guest: i64,
    #[serde(rename = "Proto")]
    pub proto: String,
    #[serde(rename = "State")]
    pub state: String,
    #[serde(rename = "Error")]
    pub error: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct PortMutationRequest {
    #[serde(rename = "sandbox")]
    pub sandbox: String,
    #[serde(rename = "spec")]
    pub spec: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct PortRequest {
    #[serde(rename = "Bind")]
    pub bind: String,
    #[serde(rename = "Guest")]
    pub guest: String,
    #[serde(rename = "UDP")]
    pub udp: bool,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct RegistryAuth {
    #[serde(rename = "Remote")]
    pub remote: String,
    #[serde(rename = "Registry")]
    pub registry: String,
    #[serde(rename = "Username")]
    pub username: String,
    #[serde(rename = "Source")]
    pub source: String,
    #[serde(rename = "HasSecret")]
    pub has_secret: bool,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct RegistryLoginRequest {
    #[serde(rename = "Registry")]
    pub registry: String,
    #[serde(rename = "Username")]
    pub username: String,
    #[serde(rename = "Secret")]
    pub secret: crate::wire::SecretInput,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ResourceLimits {
    #[serde(rename = "MinMemoryMB")]
    pub min_memory_mb: u64,
    #[serde(rename = "MaxMemoryMB")]
    pub max_memory_mb: u64,
    #[serde(rename = "MinDiskSizeMiB")]
    pub min_disk_size_mib: u64,
    #[serde(rename = "MaxDiskSizeMiB")]
    pub max_disk_size_mib: u64,
    #[serde(rename = "DefaultDiskSizeMiB")]
    pub default_disk_size_mib: u64,
    #[serde(rename = "MaxVCPUs")]
    pub max_vcpus: i64,
    #[serde(rename = "DefaultDevContainersMemoryMiB")]
    pub default_dev_containers_memory_mib: u64,
    #[serde(rename = "DefaultDevContainersDiskMiB")]
    pub default_dev_containers_disk_mib: u64,
    #[serde(rename = "DefaultDevContainersVCPUs")]
    pub default_dev_containers_vcpus: i64,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct Rule {
    #[serde(rename = "Remote")]
    pub remote: String,
    #[serde(rename = "Sandbox")]
    pub sandbox: String,
    #[serde(rename = "Action")]
    pub action: String,
    #[serde(rename = "Target")]
    pub target: String,
    #[serde(rename = "Proto")]
    pub proto: String,
    #[serde(rename = "Ports")]
    pub ports: String,
    #[serde(rename = "Source")]
    pub source: String,
    #[serde(rename = "Policy")]
    pub policy: String,
    #[serde(rename = "Error")]
    pub error: bool,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct RuleRequest {
    #[serde(rename = "Sandbox")]
    pub sandbox: String,
    #[serde(rename = "Action")]
    pub action: String,
    #[serde(rename = "Target")]
    pub target: String,
    #[serde(rename = "Proto")]
    pub proto: String,
    #[serde(rename = "Ports")]
    pub ports: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct Sandbox {
    #[serde(rename = "Remote")]
    pub remote: String,
    #[serde(rename = "ActiveAvailable")]
    pub active_available: bool,
    #[serde(rename = "ActiveMemMB")]
    pub active_mem_mb: u64,
    #[serde(rename = "ActiveVCPUs")]
    pub active_vcpus: i64,
    #[serde(rename = "RestartRequired")]
    pub restart_required: bool,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "State")]
    pub state: String,
    #[serde(rename = "PID")]
    pub pid: i64,
    #[serde(rename = "Image")]
    pub image: String,
    #[serde(rename = "Runtime")]
    pub runtime: String,
    #[serde(rename = "Kernel")]
    pub kernel: String,
    #[serde(rename = "Secrets")]
    pub secrets: String,
    #[serde(rename = "SecretCount")]
    pub secret_count: i64,
    #[serde(rename = "RW")]
    pub rw: bool,
    #[serde(rename = "RWLayer")]
    pub rw_layer: String,
    #[serde(rename = "DiskSizeMiB")]
    pub disk_size_mib: u64,
    #[serde(rename = "Net")]
    pub net: bool,
    #[serde(rename = "GVProxy")]
    pub gv_proxy: String,
    #[serde(rename = "NetPolicy")]
    pub net_policy: String,
    #[serde(rename = "AllowLocal")]
    pub allow_local: bool,
    #[serde(rename = "Proxy")]
    pub proxy: String,
    #[serde(rename = "NoProxy")]
    pub no_proxy: String,
    #[serde(rename = "ProxyEnforce")]
    pub proxy_enforce: bool,
    #[serde(rename = "Shares")]
    pub shares: i64,
    #[serde(rename = "Ports")]
    pub ports: i64,
    #[serde(rename = "MemMB")]
    pub mem_mb: u64,
    #[serde(rename = "VCPUs")]
    pub vcpus: i64,
    #[serde(rename = "ProcessIsolation")]
    pub process_isolation: String,
    #[serde(rename = "SSH")]
    pub ssh: bool,
    #[serde(rename = "DevContainers")]
    pub dev_containers: bool,
    #[serde(rename = "DevContainersImage")]
    pub dev_containers_image: String,
    #[serde(rename = "DevContainersRWLayer")]
    pub dev_containers_rw_layer: String,
    #[serde(rename = "DevContainersDiskMiB")]
    pub dev_containers_disk_mib: u64,
    #[serde(rename = "Dir")]
    pub dir: String,
    #[serde(rename = "ConfigPath")]
    pub config_path: String,
    #[serde(rename = "Updated")]
    pub updated: String,
    #[serde(rename = "ConfigError")]
    pub config_error: bool,
    #[serde(rename = "TXBytes")]
    pub tx_bytes: u64,
    #[serde(rename = "RXBytes")]
    pub rx_bytes: u64,
    #[serde(rename = "DroppedPackets")]
    pub dropped_packets: u64,
    #[serde(rename = "TrafficAvailable")]
    pub traffic_available: bool,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SandboxConfigRequest {
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "MemMB")]
    pub mem_mb: u64,
    #[serde(rename = "VCPUs")]
    pub vcpus: i64,
    #[serde(rename = "ProcessIsolation")]
    pub process_isolation: String,
    #[serde(rename = "SSH")]
    pub ssh: bool,
    #[serde(rename = "DevContainers")]
    pub dev_containers: bool,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct Secret {
    #[serde(rename = "Remote")]
    pub remote: String,
    #[serde(rename = "Sandbox")]
    pub sandbox: String,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "State")]
    pub state: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SecretRequest {
    #[serde(rename = "Sandbox")]
    pub sandbox: String,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "Value")]
    pub value: crate::wire::SecretInput,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SharePlan {
    #[serde(rename = "Sandbox")]
    pub sandbox: String,
    #[serde(rename = "Tag")]
    pub tag: String,
    #[serde(rename = "Spec")]
    pub spec: String,
    #[serde(rename = "Mountpoint")]
    pub mountpoint: String,
    #[serde(rename = "Replace")]
    pub replace: bool,
    #[serde(rename = "Live")]
    pub live: bool,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ShareRequest {
    #[serde(rename = "Sandbox")]
    pub sandbox: String,
    #[serde(rename = "Tag")]
    pub tag: String,
    #[serde(rename = "Path")]
    pub path: String,
    #[serde(rename = "Mountpoint")]
    pub mountpoint: String,
    #[serde(rename = "Owner")]
    pub owner: String,
    #[serde(rename = "ReadOnly")]
    pub read_only: bool,
    #[serde(rename = "Replace")]
    pub replace: bool,
    #[serde(rename = "Running")]
    pub running: bool,
    #[serde(rename = "CurrentGuest")]
    pub current_guest: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct Traffic {
    #[serde(rename = "Remote")]
    pub remote: String,
    #[serde(rename = "Sandbox")]
    pub sandbox: String,
    #[serde(rename = "Host")]
    pub host: String,
    #[serde(rename = "Address")]
    pub address: String,
    #[serde(rename = "Protocol")]
    pub protocol: String,
    #[serde(rename = "Port")]
    pub port: u16,
    #[serde(rename = "Allowed")]
    pub allowed: bool,
    #[serde(rename = "TXBytes")]
    pub tx_bytes: u64,
    #[serde(rename = "RXBytes")]
    pub rx_bytes: u64,
    #[serde(rename = "TXPackets")]
    pub tx_packets: u64,
    #[serde(rename = "RXPackets")]
    pub rx_packets: u64,
    #[serde(rename = "FirstSeen")]
    pub first_seen: String,
    #[serde(rename = "LastSeen")]
    pub last_seen: String,
}
